### ISSUE TITLE
API요청시 헤더

### ISSUE THREAD

**Issue by Goldenprevue** [wanted-pre-onboarding-team12/pre-onboarding-11th-3-12#9]
깃허브 공식문서에서는 헤더에 이걸 담아서 요청하라고 나오는데요
`-H "X-GitHub-Api-Version: 2022-11-28" `
aws 정책같은 느낌인데 헤더에 담지 않아도 되긴합니다 
여러분들은 헤더에 담아서 보내나요?

**Comment by ncb6206** [comment]
저는 안보냈습니다!
